### ISSUE TITLE
Setting openpaas-james project up

### ISSUE THREAD

**Issue by chibenwa** [linagora/openpaas-james#2]
Checklist:

Applications:

 - [x] Memory flavour to ease testing
 - [x] Distributed flavour - no LDAP
 - [x] Distributed flavour - LDAP

Packaging:

 - [x] JIB
 - [x] Able to use the CLI
 - [x] Able to use glowroot
 - [x] Deployment tests are run as part of the build

CI (Jenkins 2):
 
 - [x] master branch testing
 - [x] GitHub PR testing
 - [x] Specific tags testing

CD (Jenkins 2):

 - [x] Publish branch-master to dockerhub upon successful master branch builds
 - [x] Publish tags to dockerhub

Features:

 - [x] JMAP's Filters/get is part of openpaas-james

Documentation:

 - [x] README
 - [x] Changelog + upgrade instructions
 - [x] ADRs

**Comment by chibenwa** [comment]
Regarding CI/CD:

```
 - [9] Jenkins 2: on-commit master branch build.

3 phase:
 - 1. Fetch apache/james-project code 
 - 2. Compile (install) at root (it will compile apache/james-project then openpaas-james)
 - 3. Run tests (mvn test) within openpaas james subfolder (no need to test james-project as it is separatedly tested.)

We should write a JenkinsFile for it...

 - [10] Publish branch-master images to dockerhub

 - [11] PR build. Rebase the PRs on master then build & test them. Build output should be visible on Github.

 - [12] Tag build. Tag & publish the relevant docker images to dockerhub.
```

**Comment by Arsnael** [comment]
Regarding CI/CD, given by Antoine:

Voici les infos sur la CI Jenkins 2 actuelle.

Le repo est sur Gitlab, je vous ai donné les droits:
https://ci.linagora.com/linagora/lgs/ci-github

Le déploiement est ici (authent par Github):
https://ci-github.linagora.com/
(par contre, les builds de James vont saturer l'unique slave...)

Au niveau technique, le point d'entrée est ici:
https://ci.linagora.com/linagora/lgs/ci-github/blob/master/jenkins.yaml#L67

ce script est exécuté au démarrage est crée un seed job qui surveille un repo Github
(https://github.com/OpenPaaS-Suite/CI-jobs)
le rôle de ce dernier est de créer:
- une vue correspondant à l'orga Github
- des jobs correspondant aux repos à builder

Par suite, le github-branch-source
plugin nous assure de créer:
- un job par MR (le reschedule est manuel sur le Jenkins)
- un job par branche
